// import { createSlice } from "@reduxjs/toolkit";
// const initialState = {
//   carts: [],
// };
// export const orderSlice = createSlice({
//   name: "order",
//   initialState,
//   // The `reducers` field lets us define reducers and generate associated actions
//   reducers: {
//     //action
//     doAddBookAction: (state, action) => {
//       alert("me me");
//     },
//   },
//   // The `extraReducers` field lets the slice handle actions defined elsewhere,
//   // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {},
// });
// export const { doAddBookAction } = orderSlice.actions;
// export default orderSlice.reducer;
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
const initialState = {
  isAuthenticated: false,
  isLoading: true,
  user: {
    email: "",
    phone: "",
    fullName: "",
    role: "",
    avatar: "",
    id: "",
  },
};
export const accountSlice = createSlice({
  name: "account",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthenticated = true;
      state.user = action.payload;
      state.isLoading = false;
    },
    doGetAccountAction: (state, action) => {
      state.isLoading = false;
      state.isAuthenticated = true;
      state.user = action.payload;
    },
    doLogoutAction: (state, action) => {
      localStorage.removeItem("access_token");
      state.isAuthenticated = false;
      state.user = {
        email: "",
        phone: "",
        fullName: "",
        role: "",
        avatar: "",
        id: "",
      };
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});
export const { doLoginAction, doGetAccountAction, doLogoutAction } =
  accountSlice.actions;
export default accountSlice.reducer;
