import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  carts: [],
};
export const orderSlice = createSlice({
  name: "order",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    //action
    doAddBookAction: (state, action) => {
      let carts = state.carts;
      console.log("🚀 ~ file: orderslice.js:13 ~ carts:", carts);
      const item = action.payload;
      console.log("🚀 ~ file: orderslice.js:15 ~ item:", item);
      let isExitsItem = carts.findIndex((c) => {
        c._id === item._id;
      });
      console.log(
        "🚀 ~ file: orderslice.js:19 ~ isExitsItem ~ isExitsItem:",
        isExitsItem
      );
      if (isExitsItem > -1) {
        carts[isExitsItem].quanlity += item.quanlity;
      } else {
        carts.push({
          quanlity: item.quanlity,
          _id: item._id,
          detail: item.detail,
        });
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});
export const { doAddBookAction } = orderSlice.actions;
export default orderSlice.reducer;
